import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { P2POffer, P2PTradeStatus, P2PTradeType, Prisma, TransactionStatus, TransactionType, User } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { QueryOffersDto } from './dto/query-offers.dto';
import { CreateOfferDto } from './dto/create-offer.dto';
import { InitiateTradeDto } from './dto/initiate-trade.dto';

type OfferWithTrader = P2POffer & { trader: User };
export interface P2POfferDto { id:string; traderName:string; traderAvatarInitial:string; traderRating:number; traderTrades:number; pricePerCoin:string; availableAmountCrypto:string; limitFiat:string; paymentMethods:string[]; isOnline:boolean; isVerified:boolean; responseTime:string; cryptoSymbol:string; fiatCurrency:string; paymentWindowMinutes:number; avgReleaseTimeMinutes:number; }

@Injectable()
export class P2pService {
  constructor(private readonly prisma: PrismaService) {}
  private decimal(value:string, field:string):Prisma.Decimal { try { const v=new Prisma.Decimal(value); if(!v.isFinite()) throw new Error(); return v; } catch { throw new BadRequestException(`${field} must be a valid number`); } }
  private toDto(o:OfferWithTrader):P2POfferDto { return { id:o.id,traderName:o.trader.username,traderAvatarInitial:o.trader.avatarInitial,traderRating:o.trader.p2pRating,traderTrades:o.trader.p2pTrades,pricePerCoin:o.pricePerCoin.toString(),availableAmountCrypto:`${o.availableAmountMin} - ${o.availableAmountMax} ${o.cryptoSymbol}`,limitFiat:`${o.limitFiatMin} - ${o.limitFiatMax}`,paymentMethods:o.paymentMethods,isOnline:o.isOnline,isVerified:o.trader.isVerified,responseTime:`~${o.avgReleaseTimeMinutes} min`,cryptoSymbol:o.cryptoSymbol,fiatCurrency:o.fiatCurrency,paymentWindowMinutes:o.paymentWindowMinutes,avgReleaseTimeMinutes:o.avgReleaseTimeMinutes }; }
  private parties(trade:{type:P2PTradeType;makerId:string;takerId:string}) { return trade.type===P2PTradeType.SELL ? {sellerId:trade.makerId,buyerId:trade.takerId} : {sellerId:trade.takerId,buyerId:trade.makerId}; }

  async findOffers(q:QueryOffersDto):Promise<P2POfferDto[]> { return (await this.prisma.p2POffer.findMany({where:{cryptoSymbol:q.cryptoSymbol,fiatCurrency:q.fiatCurrency,type:q.type,isOnline:true},include:{trader:true},orderBy:{createdAt:'desc'}})).map(o=>this.toDto(o)); }
  async createOffer(traderId:string,dto:CreateOfferDto):Promise<P2POfferDto> { const p=this.decimal(dto.pricePerCoin,'pricePerCoin'),cmin=this.decimal(dto.availableAmountMin,'availableAmountMin'),cmax=this.decimal(dto.availableAmountMax,'availableAmountMax'),fmin=this.decimal(dto.limitFiatMin,'limitFiatMin'),fmax=this.decimal(dto.limitFiatMax,'limitFiatMax'); if(p.lte(0)) throw new BadRequestException('Offer price must be greater than zero'); if(cmin.lte(0)||cmax.lte(0)||cmin.gt(cmax)) throw new BadRequestException('Invalid crypto amount range'); if(fmin.lte(0)||fmax.lte(0)||fmin.gt(fmax)) throw new BadRequestException('Invalid fiat limit range'); if(!dto.paymentMethods.length) throw new BadRequestException('At least one payment method is required'); if(fmin.gt(cmax.mul(p))||fmax.lt(cmin.mul(p))) throw new BadRequestException('Fiat limits do not overlap the offered crypto range'); return this.toDto(await this.prisma.p2POffer.create({data:{traderId,...dto},include:{trader:true}})); }

  async initiateTrade(userId:string,dto:InitiateTradeDto) {
    const offer=await this.prisma.p2POffer.findUnique({where:{id:dto.offerId}}); if(!offer) throw new NotFoundException('Offer not found'); if(!offer.isOnline) throw new BadRequestException('Offer is no longer available'); if(offer.traderId===userId) throw new BadRequestException('You cannot trade against your own offer');
    const amount=this.decimal(dto.amount,'amount'); if(amount.lte(0)||amount.lt(offer.availableAmountMin)||amount.gt(offer.availableAmountMax)) throw new BadRequestException('Trade amount is outside the offer crypto limits'); const fiat=amount.mul(offer.pricePerCoin); if(fiat.lt(offer.limitFiatMin)||fiat.gt(offer.limitFiatMax)) throw new BadRequestException('Trade amount is outside the offer fiat limits');
    const sellerId=offer.type===P2PTradeType.SELL?offer.traderId:userId;
    return this.prisma.$transaction(async tx=>{
      const reserved=await tx.cryptoAsset.updateMany({where:{userId:sellerId,symbol:offer.cryptoSymbol,balance:{gte:amount}},data:{balance:{decrement:amount}}}); if(reserved.count!==1) throw new BadRequestException('Seller has insufficient available crypto balance');
      return tx.p2PTrade.create({data:{offerId:offer.id,makerId:offer.traderId,takerId:userId,type:offer.type,cryptoSymbol:offer.cryptoSymbol,fiatCurrency:offer.fiatCurrency,pricePerCoin:offer.pricePerCoin,cryptoAmount:amount,fiatAmount:fiat,paymentMethods:offer.paymentMethods,status:P2PTradeStatus.AWAITING_PAYMENT,escrowFundedAt:new Date(),expiresAt:new Date(Date.now()+offer.paymentWindowMinutes*60000)}});
    });
  }

  private async participantTrade(userId:string,id:string){ const t=await this.prisma.p2PTrade.findUnique({where:{id}}); if(!t) throw new NotFoundException('Trade not found'); if(t.makerId!==userId&&t.takerId!==userId) throw new ForbiddenException('You are not a participant in this trade'); return t; }
  async markPayment(userId:string,id:string){ const t=await this.participantTrade(userId,id),{buyerId}=this.parties(t); if(buyerId!==userId) throw new ForbiddenException('Only the buyer can mark payment'); if(t.status!==P2PTradeStatus.AWAITING_PAYMENT) throw new BadRequestException('Trade is not awaiting payment'); if(t.expiresAt<=new Date()){ await this.expireTrade(t.id); throw new BadRequestException('Payment window has expired'); } const changed=await this.prisma.p2PTrade.updateMany({where:{id:t.id,status:P2PTradeStatus.AWAITING_PAYMENT,escrowReleasedAt:null},data:{status:P2PTradeStatus.PAYMENT_MARKED,paymentMarkedAt:new Date()}}); if(changed.count!==1) throw new BadRequestException('Trade state changed; refresh and try again'); return this.prisma.p2PTrade.findUnique({where:{id:t.id}}); }

  private async refundEscrow(tx:Prisma.TransactionClient,t:any){ const {sellerId}=this.parties(t); if(!t.escrowFundedAt) throw new BadRequestException('Trade escrow was not funded'); const refunded=await tx.cryptoAsset.updateMany({where:{userId:sellerId,symbol:t.cryptoSymbol},data:{balance:{increment:t.cryptoAmount}}}); if(refunded.count!==1) throw new BadRequestException('Seller wallet for escrow refund is unavailable'); }
  private async expireTrade(id:string){ return this.prisma.$transaction(async tx=>{ const t=await tx.p2PTrade.findUnique({where:{id}}); if(!t||t.status!==P2PTradeStatus.AWAITING_PAYMENT||t.escrowReleasedAt) return t; const claimed=await tx.p2PTrade.updateMany({where:{id,status:P2PTradeStatus.AWAITING_PAYMENT,escrowReleasedAt:null,expiresAt:{lt:new Date()}},data:{status:P2PTradeStatus.EXPIRED,escrowReleasedAt:new Date()}}); if(claimed.count!==1) return tx.p2PTrade.findUnique({where:{id}}); await this.refundEscrow(tx,t); return tx.p2PTrade.findUnique({where:{id}}); }); }
  async cancelTrade(userId:string,id:string){ const t=await this.participantTrade(userId,id); if(t.status!==P2PTradeStatus.AWAITING_PAYMENT) throw new BadRequestException('Only unpaid trades can be cancelled'); return this.prisma.$transaction(async tx=>{ const claimed=await tx.p2PTrade.updateMany({where:{id,status:P2PTradeStatus.AWAITING_PAYMENT,escrowReleasedAt:null},data:{status:P2PTradeStatus.CANCELLED,cancelledAt:new Date(),escrowReleasedAt:new Date()}}); if(claimed.count!==1) throw new BadRequestException('Trade state changed; refresh and try again'); await this.refundEscrow(tx,t); return tx.p2PTrade.findUnique({where:{id}}); }); }
  async disputeTrade(userId:string,id:string){ const t=await this.participantTrade(userId,id); if(t.status!==P2PTradeStatus.PAYMENT_MARKED) throw new BadRequestException('A dispute can only be opened after payment is marked'); const changed=await this.prisma.p2PTrade.updateMany({where:{id,status:P2PTradeStatus.PAYMENT_MARKED,escrowReleasedAt:null},data:{status:P2PTradeStatus.DISPUTED,disputedAt:new Date()}}); if(changed.count!==1) throw new BadRequestException('Trade state changed; refresh and try again'); return this.prisma.p2PTrade.findUnique({where:{id}}); }

  async releaseCrypto(userId:string,id:string){ const t=await this.participantTrade(userId,id),{sellerId,buyerId}=this.parties(t); if(sellerId!==userId) throw new ForbiddenException('Only the seller can release crypto'); if(t.status!==P2PTradeStatus.PAYMENT_MARKED) throw new BadRequestException('Crypto can only be released after payment is marked'); return this.prisma.$transaction(async tx=>{ const changed=await tx.p2PTrade.updateMany({where:{id,status:P2PTradeStatus.PAYMENT_MARKED,escrowReleasedAt:null},data:{status:P2PTradeStatus.COMPLETED,completedAt:new Date(),escrowReleasedAt:new Date()}}); if(changed.count!==1) throw new BadRequestException('Trade has already been settled or its state changed'); const buyerAsset=await tx.cryptoAsset.findUnique({where:{userId_symbol:{userId:buyerId,symbol:t.cryptoSymbol}}}); if(!buyerAsset) throw new BadRequestException('Buyer wallet for this asset is unavailable'); await tx.cryptoAsset.update({where:{id:buyerAsset.id},data:{balance:{increment:t.cryptoAmount}}}); await tx.transaction.create({data:{userId:buyerId,type:TransactionType.P2P_BUY,cryptoSymbol:t.cryptoSymbol,cryptoAmount:t.cryptoAmount,fiatAmount:t.fiatAmount,fiatCurrency:t.fiatCurrency,status:TransactionStatus.COMPLETED,description:`P2P purchase ${t.id}`}}); await tx.transaction.create({data:{userId:sellerId,type:TransactionType.P2P_SELL,cryptoSymbol:t.cryptoSymbol,cryptoAmount:t.cryptoAmount,fiatAmount:t.fiatAmount,fiatCurrency:t.fiatCurrency,status:TransactionStatus.COMPLETED,description:`P2P sale ${t.id}`}}); await tx.user.update({where:{id:buyerId},data:{p2pTrades:{increment:1}}}); await tx.user.update({where:{id:sellerId},data:{p2pTrades:{increment:1}}}); return tx.p2PTrade.findUnique({where:{id}}); }); }

  async getMyTrades(userId:string){ const expired=await this.prisma.p2PTrade.findMany({where:{status:P2PTradeStatus.AWAITING_PAYMENT,escrowReleasedAt:null,expiresAt:{lt:new Date()},OR:[{makerId:userId},{takerId:userId}]},select:{id:true}}); for(const t of expired) await this.expireTrade(t.id); return this.prisma.p2PTrade.findMany({where:{OR:[{makerId:userId},{takerId:userId}]},orderBy:{createdAt:'desc'}}); }
}
