
import React, { useState, useEffect, useCallback } from 'react';
import { X, Zap, AlertTriangle } from 'lucide-react';
import { apiService } from '../services/apiService';
import { MarketTrendAnalysis } from '../types';
import LoadingSpinner from './LoadingSpinner';

interface MarketAnalysisModalProps {
  cryptoSymbol: string;
  cryptoName: string;
  onClose: () => void;
}

const MarketAnalysisModal: React.FC<MarketAnalysisModalProps> = ({ cryptoSymbol, cryptoName, onClose }) => {
  const [analysis, setAnalysis] = useState<MarketTrendAnalysis | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchAnalysis = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const result = await apiService.getMarketTrendExplanation(cryptoSymbol);
      setAnalysis(result);
    } catch (err: any) {
      console.error("MarketAnalysisModal Error:", err);
      if (err.message && err.message.includes("not configured")) {
        setError("Market analysis feature is currently unavailable on this server.");
      } else if (err.message && err.message.includes("429")) { // Too Many Requests
        setError("Market analysis service is temporarily busy. Please try again later.");
      }
      else {
        setError("Could not fetch market analysis. Please try again later.");
      }
    } finally {
      setIsLoading(false);
    }
  }, [cryptoSymbol]);

  useEffect(() => {
    fetchAnalysis();
  }, [fetchAnalysis]);

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-slate-800 border border-slate-700 rounded-2xl p-6 w-full max-w-md shadow-xl max-h-[80vh] flex flex-col">
        <div className="flex justify-between items-center mb-4">
          <div className="flex items-center space-x-2">
            <Zap className="w-6 h-6 text-blue-400" />
            <h3 className="text-white font-semibold text-lg">Market Insights: {cryptoName} ({cryptoSymbol})</h3>
          </div>
          <button 
            onClick={onClose}
            className="text-gray-400 hover:text-white transition-colors"
            aria-label="Close market analysis"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="flex-grow overflow-y-auto pr-2 -mr-2 scrollbar-thin scrollbar-thumb-slate-600 scrollbar-track-slate-800">
          {isLoading && <LoadingSpinner text={`Analyzing ${cryptoSymbol} trends...`} />}
          
          {error && (
            <div className="bg-red-500/10 text-red-300 p-4 rounded-lg flex items-start space-x-3">
              <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5 flex-shrink-0" />
              <div>
                <h4 className="font-semibold text-red-400">Analysis Error</h4>
                <p className="text-sm">{error}</p>
              </div>
            </div>
          )}

          {!isLoading && !error && analysis && (
            <div className="space-y-3">
              <p className="text-gray-300 leading-relaxed text-sm whitespace-pre-line">{analysis.explanation}</p>
              <p className="text-xs text-gray-500 text-right">
                Analysis generated by AI on: {new Date(analysis.generatedAt).toLocaleString()}
              </p>
              <p className="text-xs text-yellow-400/80 bg-yellow-500/10 p-2 rounded-md">
                <AlertTriangle className="inline w-3 h-3 mr-1" />
                This information is AI-generated and for informational purposes only. It is not financial advice. Always do your own research.
              </p>
            </div>
          )}
        </div>

        <button 
          onClick={onClose}
          className="mt-6 w-full bg-slate-600 hover:bg-slate-500 text-white py-2.5 rounded-lg font-medium transition-colors"
        >
          Close
        </button>
      </div>
    </div>
  );
};

export default MarketAnalysisModal;
